-- MySQL Script generated by MySQL Workbench
-- 01/21/17 20:23:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fork_you_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fork_you_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fork_you_db` DEFAULT CHARACTER SET utf8 ;
USE `fork_you_db` ;

-- -----------------------------------------------------
-- Table `fork_you_db`.`Contact_Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Contact_Info` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Contact_Info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `street` VARCHAR(120) NULL,
  `postal_code` INT NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(20) NULL,
  `phone_number` INT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Food_Creator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Food_Creator` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Food_Creator` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Food_Creator_Contact_Info_idx` (`id` ASC),
  CONSTRAINT `fk_Food_Creator_Contact_Info`
    FOREIGN KEY (`id`)
    REFERENCES `fork_you_db`.`Contact_Info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Category` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Food` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Food` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `for_sell` INT NULL,
  `price` DECIMAL(5) NULL,
  `id_creator` INT NOT NULL,
  `id_category` INT NOT NULL,
  PRIMARY KEY (`id`, `id_creator`, `id_category`),
  INDEX `fk_Food_Food_Creator1_idx` (`id_creator` ASC),
  INDEX `fk_Food_Category1_idx` (`id_category` ASC),
  CONSTRAINT `fk_Food_Food_Creator1`
    FOREIGN KEY (`id_creator`)
    REFERENCES `fork_you_db`.`Food_Creator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Food_Category1`
    FOREIGN KEY (`id_category`)
    REFERENCES `fork_you_db`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Dish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Dish` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Dish` (
  `id` INT NOT NULL,
  `id_recipe` INT NOT NULL,
  PRIMARY KEY (`id`, `id_recipe`),
  INDEX `fk_Dish_Food1_idx` (`id` ASC),
  INDEX `fk_Dish_Recipe1_idx` (`id_recipe` ASC),
  CONSTRAINT `fk_Dish_Food1`
    FOREIGN KEY (`id`)
    REFERENCES `fork_you_db`.`Food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dish_Recipe1`
    FOREIGN KEY (`id_recipe`)
    REFERENCES `fork_you_db`.`Recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Recipe` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Recipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `last_update` DATETIME NULL,
  `id_creator` INT NOT NULL,
  `id_dish` INT NOT NULL,
  PRIMARY KEY (`id`, `id_creator`, `id_dish`),
  INDEX `fk_Recipe_Food_Creator1_idx` (`id_creator` ASC),
  INDEX `fk_Recipe_Dish1_idx` (`id_dish` ASC),
  CONSTRAINT `fk_Recipe_Food_Creator1`
    FOREIGN KEY (`id_creator`)
    REFERENCES `fork_you_db`.`Food_Creator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipe_Dish1`
    FOREIGN KEY (`id_dish`)
    REFERENCES `fork_you_db`.`Dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Drink`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Drink` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Drink` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Drink_Dish1_idx` (`id` ASC),
  CONSTRAINT `fk_Drink_Dish1`
    FOREIGN KEY (`id`)
    REFERENCES `fork_you_db`.`Dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Ingredient` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Ingredient` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ingredient_Food1_idx` (`id` ASC),
  CONSTRAINT `fk_Ingredient_Food1`
    FOREIGN KEY (`id`)
    REFERENCES `fork_you_db`.`Food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Brand` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Brand` (
  `id` INT NOT NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Brand_Food_Creator1_idx` (`id` ASC),
  CONSTRAINT `fk_Brand_Food_Creator1`
    FOREIGN KEY (`id`)
    REFERENCES `fork_you_db`.`Food_Creator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Location` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Location` (
  `id` INT NOT NULL,
  `id_owner` INT NOT NULL,
  PRIMARY KEY (`id`, `id_owner`),
  INDEX `fk_Location_Contact_Info1_idx` (`id` ASC),
  INDEX `fk_Location_Brand1_idx` (`id_owner` ASC),
  CONSTRAINT `fk_Location_Contact_Info1`
    FOREIGN KEY (`id`)
    REFERENCES `fork_you_db`.`Contact_Info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Location_Brand1`
    FOREIGN KEY (`id_owner`)
    REFERENCES `fork_you_db`.`Brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Location_sells_Food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Location_sells_Food` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Location_sells_Food` (
  `id_location` INT NOT NULL,
  `id_food` INT NOT NULL,
  PRIMARY KEY (`id_location`, `id_food`),
  INDEX `fk_Location_has_Food_Food1_idx` (`id_food` ASC),
  INDEX `fk_Location_has_Food_Location1_idx` (`id_location` ASC),
  CONSTRAINT `fk_Location_has_Food_Location1`
    FOREIGN KEY (`id_location`)
    REFERENCES `fork_you_db`.`Location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Location_has_Food_Food1`
    FOREIGN KEY (`id_food`)
    REFERENCES `fork_you_db`.`Food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Food_has_Dish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Food_has_Dish` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Food_has_Dish` (
  `id_food` INT NOT NULL,
  `id_dish` INT NOT NULL,
  PRIMARY KEY (`id_food`, `id_dish`),
  INDEX `fk_Food_has_Dish_Dish1_idx` (`id_dish` ASC),
  INDEX `fk_Food_has_Dish_Food1_idx` (`id_food` ASC),
  CONSTRAINT `fk_Food_has_Dish_Food1`
    FOREIGN KEY (`id_food`)
    REFERENCES `fork_you_db`.`Food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Food_has_Dish_Dish1`
    FOREIGN KEY (`id_dish`)
    REFERENCES `fork_you_db`.`Dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`User` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`User` (
  `id` INT NOT NULL,
  `password` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Food_Creator1_idx` (`id` ASC),
  CONSTRAINT `fk_User_Food_Creator1`
    FOREIGN KEY (`id`)
    REFERENCES `fork_you_db`.`Food_Creator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`User_Wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`User_Wishlist` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`User_Wishlist` (
  `id_food` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_food`, `id_user`),
  INDEX `fk_Food_has_User_User1_idx` (`id_user` ASC),
  INDEX `fk_Food_has_User_Food1_idx` (`id_food` ASC),
  CONSTRAINT `fk_Food_has_User_Food1`
    FOREIGN KEY (`id_food`)
    REFERENCES `fork_you_db`.`Food` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Food_has_User_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `fork_you_db`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fork_you_db`.`Followers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fork_you_db`.`Followers` ;

CREATE TABLE IF NOT EXISTS `fork_you_db`.`Followers` (
  `id_user` INT NOT NULL,
  `id_followed` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_followed`),
  INDEX `fk_User_has_Food_Creator_Food_Creator1_idx` (`id_followed` ASC),
  INDEX `fk_User_has_Food_Creator_User1_idx` (`id_user` ASC),
  CONSTRAINT `fk_User_has_Food_Creator_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `fork_you_db`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Food_Creator_Food_Creator1`
    FOREIGN KEY (`id_followed`)
    REFERENCES `fork_you_db`.`Food_Creator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
